### ISSUE TITLE
VerifyRPC fails when inheriting from a WIG class

### ISSUE THREAD

**Issue by Tarmil** [dotnet-websharper/core#1010]
The specific case is this:

* WIG code:
    ```fsharp
    // Base class without a constructor
    let A = Class "A"

    // Inheriting class with a constructor
    let B =
        Class "B"
        |=> Inherits A
        |+> Static [Constructor T<unit>]
    ```

* F# code using the above WIG library:

    ```fsharp
    type C() =
        inherit B()
    ```

Error message:

```
WebSharper error FS9001: Global error 'The given key was not present in the dictionary.' at 
   at WebSharper.Compiler.MergedDictionary`2.get_Item(TKey key)
   at <StartupCode$WebSharper-Compiler>.$Compilation.isWebControl@1715(Compilation this, ClassInfo cls)
   at WebSharper.Compiler.Compilation.VerifyRPCs()
   at WebSharper.Compiler.FSharp.WebSharperFSharpCompiler.Compile(Task`1 prevMeta, String[] argv, WsConfig config, String assemblyName)
   at WebSharper.FSharp.Program.Compile$cont@120-1(WsConfig config, String thisName, WebSharperFSharpCompiler compiler, Boolean isBundleOnly, FSharpList`1 paths, AssemblyResolver aR, Unit unitVar)
   at WebSharper.FSharp.Program.Compile$cont@70(WsConfig config, WarnSettings warnSettings, String thisName, Unit unitVar)
   at WebSharper.FSharp.Program.compileMain$cont@304(String[] argv, Unit unitVar)
   at WebSharper.FSharp.Program.main(String[] argv)
```

The error disappears if I add a constructor to `A`. It looks like the compiler is trying to go up the constructor chain but fails when it can't find a constructor for `A`.

**Comment by Tarmil** [comment]
Actually the error disappears if I add any kind of member to `A`, not necessarily a constructor. The root f the problem seems to be that the class is not added to the metadata if it has no members, specifically here: https://github.com/dotnet-websharper/core/blob/1b6b067172e7e91cae0d92fc632a024405f60a3e/src/compiler/WebSharper.Compiler/Reflector.fs#L270

**Comment by Tarmil** [comment]
We discussed this with @Jand42 and concluded that since Reflector is only used for WIG, we can probably just remove the above line: the only classes in a WIG assembly that shouldn't be added to the metadata are resources, and those are already treated separately.
