### ISSUE TITLE
Binary Serialization is being removed

### ISSUE THREAD

**Issue by TheAngryByrd** [dotnet-websharper/core#1411]
I installed [dotnet preview 9](https://dotnet.microsoft.com/en-us/download/dotnet/9.0) and with `DOTNET_ROLL_FORWARD_TO_PRERELEASE=1` I'm getting this error during build.

```
       Using "WebSharperTask" task from assembly "C:\Users\jimmy\.nuget\packages\websharper.fsharp\6.1.7.441-net8\build\/../tools/netstandard2.0/WebSharper.MSBuild.FSharp.dll".
       Task "WebSharperTask"
         C:\Users\jimmy\.nuget\packages\websharper.fsharp\6.1.7.441-net8\build\/../tools/net8.0/win-x64/wsfsc.exe "@C:\Users\jimmy\AppData\Local\Temp\tmpsyctnf.tmp"
         Unhandled exception. System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
            at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
            at WebSharper.FSharp.NamedPipeClient.sendCompileCommand(String[] args)
            at WebSharper.FSharp.Program.main(String[] argv)
 28:148>C:\Users\jimmy\.nuget\packages\websharper.fsharp\6.1.7.441-net8\build\WebSharper.FSharp.targets(50,5): error MSB6006: "wsfsc.exe" exited with code -532462766.
 ```
 
 ---
 
 Binary Formatter has been doing a slow obsolete for a while:
 - [BinaryFormatter Obsoletion Strategy](https://github.com/dotnet/designs/blob/main/accepted%2F2020%2Fbetter-obsoletion%2Fbinaryformatter-obsoletion.md)
 - https://github.com/dotnet/runtime/issues/98245

**Comment by granicz** [comment]
I am not up to date on the current serialization options, @TheAngryByrd - what's your take on the best way forward?

**Comment by TheAngryByrd** [comment]
Since `ArgsType` seems to be record with string array:

https://github.com/dotnet-websharper/core/blob/35c354b583b6046c75865f7f33d9bf08919ad5af/src/compiler/WebSharper.Compiler/WsFscServiceCommon.fs#L6

Replacing [BinaryFormatter](https://github.com/search?q=repo%3Adotnet-websharper%2Fcore%20binaryformatter&type=code) calls it with something like [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json?view=net-8.0) should be fairly straight forward.

**Comment by granicz** [comment]
OK, had a quick look, the offending piece is in the Booster communication code, and indeed should be quick to change it to use a more appropriate serializer. /cc @Jooseppi12

**Comment by granicz** [comment]
@Jooseppi12 Is this released, and if so, what version? If not, let's roll it out.

**Comment by Jooseppi12** [comment]
This is released for the WebSharper 8 packages on our GitHub feed, but was not backported to the websharper6 branch

**Comment by granicz** [comment]
OK, keeping this ticket open for the WS6 port as well.
