### ISSUE TITLE
Once installed .net 9 preview, wsfsc not working!!

### ISSUE THREAD

**Issue by ingted** [dotnet-websharper/core#1414]
The projects are not changed (targeting .net version/websharper lib references...) but not able to build after .net 9 preview installed.

In event viewer, application log:
```
Application: wsfsc.exe
CoreCLR Version: 9.0.24.40507
.NET Version: 9.0.0-preview.7.24405.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.PlatformNotSupportedException: BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at WebSharper.FSharp.NamedPipeClient.sendCompileCommand(String[] args)
   at WebSharper.FSharp.Program.main(String[] argv)
```

Error during build process for a websharper project:
```
C:\Users\anibal\.nuget\packages\websharper.fsharp\6.1.5.317\build\WebSharper.FSharp.targets(50,5): error MSB6006: "wsfsc.exe" exited with code -532462766. [G:\coldfar_py\sharftrade7\
FAkka.Server\FAkka.Server.fsproj]
```

**Comment by granicz** [comment]
Related to https://github.com/dotnet-websharper/core/issues/1411

**Comment by Jooseppi12** [comment]
@ingted There should be a new version on nuget (6.1.7.476) out there to remove the usage of BinaryFormatter for WebSharper 6
